# Generated by Django 4.1.1 on 2022-10-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='grandtotal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='shipping',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
